/** Words on a tournament website, in English and Arabic (from docs/prototype play-event-site). */
const en = {
  dir: 'ltr' as 'ltr' | 'rtl',
  nav: { home: 'Home', tournaments: 'Tournaments', standings: 'Standings', rules: 'Rules', faq: 'FAQ' },
  signin: 'Sign in', join: 'Create account', lang: 'العربية', myMatches: 'My matches', signout: 'Sign out', menu: 'Menu',
  browse: 'Browse tournaments', how: 'How it works',
  players: 'players registered', tours: 'tournaments', prize: 'in prizes',
  featured: 'Tournaments', featuredP: 'Register before places run out.', all: 'See all tournaments', noneYet: 'No tournaments yet. Check back soon.',
  howT: 'From sign-up to the final',
  steps: [['Create your account', 'Sign up with your email or phone number. We send you a code; there’s no password to remember.'], ['Register for a tournament', 'Pick a game, check the schedule and take a place.'], ['Play and report', 'Play your match, then upload a screenshot of the result.']] as [string, string][],
  sponsors: 'Our partners', startsIn: 'in',
  live: 'Live', reg: 'Registration open', soon: 'Coming soon', closed: 'Registration closed', ended: 'Ended', cancelled: 'Cancelled',
  register: 'Register', details: 'Details', placesLeft: (n: number) => `${n} ${n === 1 ? 'place' : 'places'} left`, full: 'Full',
  startsOn: 'Starts', format: 'Format', platform: 'Platform', prizes: 'Prizes', regCloses: 'Registration closes', regOpens: 'Registration opens', checkIn: 'Check-in', bestOf: (n: number) => `Best of ${n}`, matches: 'Matches', teamSize: (n: number) => (n > 1 ? `Teams of ${n}` : 'Solo'), entryFee: 'Entry fee', free: 'Free', countries: 'Open to', anywhere: 'Players anywhere', verifiedOnly: 'Verified players only',
  overview: 'Overview', bracket: 'Bracket', participants: 'Participants', rules: 'Rules', standingsTab: 'Standings',
  schedule: 'Schedule', tStarts: 'Tournament starts', tEnds: 'Tournament ends',
  place: (n: number) => (n === 1 ? '1st' : n === 2 ? '2nd' : n === 3 ? '3rd' : `${n}th`),
  standT: 'Standings', standP: 'Tables for round robin and Swiss tournaments, and final places for the others.', team: 'Team', player: 'Player', country: 'Country', p: 'P', w: 'W', l: 'L', diff: '+/−', pts: 'Pts', noStandings: 'Standings appear here once a tournament starts.',
  footAbout: 'Open esports tournaments.', explore: 'Explore', help: 'Help', follow: 'Follow us', powered: 'Powered by zemmz Play',
  allGames: 'All games', allStatus: 'Any status', noMatch: 'No tournaments match. Try another game or status.',
  awaiting: 'To be decided', bye: 'Bye', notStarted: 'The bracket is drawn when the tournament starts.', nobody: 'Nobody has registered yet.',
  // sign in
  signinSub: 'Enter your email or mobile number and we’ll send you a code.', target: 'Email or mobile number', targetHint: 'For a mobile number, include the country code, like +965 5000 0000.', sendCode: 'Send code',
  codeT: 'Enter the code', codeSub: (t: string) => `We sent a 6-digit code to ${t}. It works for 10 minutes.`, code: 'Code', verify: 'Continue', resend: 'Send a new code', otherTarget: 'Use a different email or number',
  badTarget: 'Enter an email address, or a mobile number with its country code.', badCode: 'That code isn’t right or has expired. Check it, or send a new one.', expired: 'That took too long. Enter your email or number again.',
  joinT: 'Create your account', joinSub: 'Tell us who you are. Your gamer tag is what opponents see in the bracket.',
  firstName: 'First name', lastName: 'Last name', gamerTag: 'Gamer tag', email: 'Email', phone: 'Mobile number', optional: 'optional',
  terms: 'I agree to the rules of this website', mustAgree: 'Agree to the rules to continue.', createBtn: 'Create account', nameReq: 'Enter your first and last name.', emailTaken: 'That email already has an account. Sign in with it instead.', tagTaken: 'That gamer tag is taken. Choose another.', phoneTaken: 'That number already has an account. Sign in with it instead.', countryReq: 'Choose your country.',
  // registering
  teamName: 'Team name', teamNameHint: 'You’re the captain. Share your team code so teammates can join.', joinTeam: 'Join a team', teamCode: 'Team code', joinBtn: 'Join team', or: 'or',
  signinToRegister: 'Sign in to register', regClosed: 'Registration is closed.', regNotOpen: (d: string) => `Registration opens ${d}.`, youreIn: 'You’re registered', payNow: (m: string) => `Pay ${m} and register`, pendingPay: 'Your place is held while you pay. Unpaid places are released after an hour.', payRetry: 'Pay the entry fee',
  feeLine: (fee: string, booking: string) => `${fee} entry fee plus ${booking} booking fee.`,
  // my matches
  welcome: (n: string) => `Signed in as ${n}.`, noEntries: 'You haven’t registered for any tournaments yet.', upcoming: 'Your tournaments', history: 'Played',
  vs: 'vs', you: 'you', resultNeeded: 'Result needed', waitingAdmin: 'Waiting for the organisers to confirm', waitingOpp: 'Waiting for your opponent', conflict: 'The organisers are checking both screenshots', proofAsked: 'The organisers asked for a clearer screenshot', won: 'Won', lost: 'Lost',
  report: 'Report result', reportT: 'Report the result', reportSub: 'Enter the score and upload a screenshot of the result screen. The organisers check it before the bracket updates.', shot: 'Result screenshot', drop: 'Choose a screenshot, or drop one here', replace: 'Choose another', submitReport: 'Send for review', cancel: 'Cancel', reported: 'Sent. The organisers will check it shortly.', reportedYou: (a: number, b: number) => `You reported ${a}–${b}.`,
  checkInBtn: 'Check in', checkInOpen: 'Check-in is open. Check in before the start or you won’t be in the bracket.', checkedIn: 'Checked in', checkInLater: (d: string) => `Check-in opens ${d}.`,
  withdrawBtn: 'Withdraw', withdrawQ: 'Withdraw from this tournament?', withdrawCaptain: 'Your whole team is withdrawn and your place is released.', withdrawSolo: 'Your place is released.', withdrawRefund: 'Your entry fee is refunded; the booking fee isn’t.', keep: 'Keep my place', withdrawn: 'You’ve withdrawn.',
  teamCodeLine: (c: string) => `Team code ${c}`, members: (n: number, of: number) => `${n} of ${of} players`,
  placeLine: (p: string) => `Finished ${p}`, noMatchYet: 'Your first match appears here when the tournament starts.', eliminated: 'Your run in this tournament is over.',
  // payments
  paid: 'Payment received. You’re registered.', payFailed: 'The payment didn’t go through and nothing was charged. Try again from My matches.', payCancelled: 'Payment cancelled. Nothing was charged.', payPending: 'We’re waiting for the payment to be confirmed. This page updates when it is.',
  offlineT: 'This website is offline', offlineP: 'The organisers are updating their plan. Check back soon.',
  verifiedNote: 'The organisers verify new accounts; some tournaments are only open to verified players.',
};
export type PlayText = typeof en;

const ar: PlayText = {
  dir: 'rtl',
  nav: { home: 'الرئيسية', tournaments: 'البطولات', standings: 'الترتيب', rules: 'القوانين', faq: 'الأسئلة الشائعة' },
  signin: 'تسجيل الدخول', join: 'إنشاء حساب', lang: 'English', myMatches: 'مبارياتي', signout: 'تسجيل الخروج', menu: 'القائمة',
  browse: 'تصفح البطولات', how: 'كيف تعمل',
  players: 'لاعب مسجّل', tours: 'بطولة', prize: 'جوائز',
  featured: 'البطولات', featuredP: 'سجّل قبل نفاد الأماكن.', all: 'عرض كل البطولات', noneYet: 'لا توجد بطولات بعد. عد قريباً.',
  howT: 'من التسجيل حتى النهائي',
  steps: [['أنشئ حسابك', 'سجّل ببريدك الإلكتروني أو رقم هاتفك. نرسل لك رمزاً، ولا حاجة لكلمة مرور.'], ['سجّل في بطولة', 'اختر لعبة، راجع الجدول واحجز مكانك.'], ['العب وأرسل النتيجة', 'العب مباراتك ثم ارفع صورة للنتيجة.']],
  sponsors: 'شركاؤنا', startsIn: 'خلال',
  live: 'مباشر', reg: 'التسجيل مفتوح', soon: 'قريباً', closed: 'أُغلق التسجيل', ended: 'انتهت', cancelled: 'أُلغيت',
  register: 'سجّل', details: 'التفاصيل', placesLeft: (n) => `${n} أماكن متبقية`, full: 'مكتملة',
  startsOn: 'تبدأ', format: 'النظام', platform: 'المنصة', prizes: 'الجوائز', regCloses: 'يغلق التسجيل', regOpens: 'يفتح التسجيل', checkIn: 'تسجيل الحضور', bestOf: (n) => `أفضل من ${n}`, matches: 'المباريات', teamSize: (n) => (n > 1 ? `فرق من ${n}` : 'فردي'), entryFee: 'رسوم الاشتراك', free: 'مجاناً', countries: 'متاحة لـ', anywhere: 'اللاعبين من أي مكان', verifiedOnly: 'اللاعبون الموثقون فقط',
  overview: 'نظرة عامة', bracket: 'الشجرة', participants: 'المشاركون', rules: 'القوانين', standingsTab: 'الترتيب',
  schedule: 'الجدول', tStarts: 'تبدأ البطولة', tEnds: 'تنتهي البطولة',
  place: (n) => `المركز ${n}`,
  standT: 'الترتيب', standP: 'جداول بطولات الدوري والنظام السويسري، والمراكز النهائية لغيرها.', team: 'الفريق', player: 'اللاعب', country: 'الدولة', p: 'لعب', w: 'فوز', l: 'خسارة', diff: 'الفارق', pts: 'نقاط', noStandings: 'يظهر الترتيب هنا بعد بدء البطولة.',
  footAbout: 'بطولات رياضات إلكترونية مفتوحة.', explore: 'استكشف', help: 'مساعدة', follow: 'تابعنا', powered: 'بدعم من zemmz Play',
  allGames: 'كل الألعاب', allStatus: 'أي حالة', noMatch: 'لا توجد بطولات مطابقة. جرّب لعبة أو حالة أخرى.',
  awaiting: 'لم يُحدد بعد', bye: 'تأهل مباشر', notStarted: 'تُرسم الشجرة عند بدء البطولة.', nobody: 'لم يسجّل أحد بعد.',
  signinSub: 'أدخل بريدك الإلكتروني أو رقم هاتفك وسنرسل لك رمزاً.', target: 'البريد الإلكتروني أو رقم الهاتف', targetHint: 'لرقم الهاتف، أضف رمز الدولة مثل ‎+965 5000 0000.', sendCode: 'أرسل الرمز',
  codeT: 'أدخل الرمز', codeSub: (t) => `أرسلنا رمزاً من 6 أرقام إلى ${t}. صالح لمدة 10 دقائق.`, code: 'الرمز', verify: 'متابعة', resend: 'أرسل رمزاً جديداً', otherTarget: 'استخدم بريداً أو رقماً آخر',
  badTarget: 'أدخل بريداً إلكترونياً، أو رقم هاتف مع رمز الدولة.', badCode: 'الرمز غير صحيح أو انتهت صلاحيته. تحقق منه أو اطلب رمزاً جديداً.', expired: 'انتهت المهلة. أدخل بريدك أو رقمك مجدداً.',
  joinT: 'أنشئ حسابك', joinSub: 'عرّفنا بنفسك. اسم اللاعب هو ما يراه خصومك في الشجرة.',
  firstName: 'الاسم الأول', lastName: 'اسم العائلة', gamerTag: 'اسم اللاعب', email: 'البريد الإلكتروني', phone: 'رقم الهاتف', optional: 'اختياري',
  terms: 'أوافق على قوانين هذا الموقع', mustAgree: 'وافق على القوانين للمتابعة.', createBtn: 'إنشاء الحساب', nameReq: 'أدخل اسمك الأول واسم العائلة.', emailTaken: 'لهذا البريد حساب بالفعل. سجّل الدخول به.', tagTaken: 'اسم اللاعب مستخدم. اختر اسماً آخر.', phoneTaken: 'لهذا الرقم حساب بالفعل. سجّل الدخول به.', countryReq: 'اختر دولتك.',
  teamName: 'اسم الفريق', teamNameHint: 'أنت قائد الفريق. شارك رمز الفريق ليتمكن زملاؤك من الانضمام.', joinTeam: 'انضم إلى فريق', teamCode: 'رمز الفريق', joinBtn: 'انضم', or: 'أو',
  signinToRegister: 'سجّل الدخول للتسجيل', regClosed: 'التسجيل مغلق.', regNotOpen: (d) => `يفتح التسجيل ${d}.`, youreIn: 'أنت مسجّل', payNow: (m) => `ادفع ${m} وسجّل`, pendingPay: 'مكانك محجوز أثناء الدفع. تُلغى الأماكن غير المدفوعة بعد ساعة.', payRetry: 'ادفع رسوم الاشتراك',
  feeLine: (fee, booking) => `رسوم اشتراك ${fee} ورسوم حجز ${booking}.`,
  welcome: (n) => `مسجّل الدخول باسم ${n}.`, noEntries: 'لم تسجّل في أي بطولة بعد.', upcoming: 'بطولاتك', history: 'مباريات سابقة',
  vs: 'ضد', you: 'أنت', resultNeeded: 'أرسل النتيجة', waitingAdmin: 'بانتظار تأكيد المنظمين', waitingOpp: 'بانتظار خصمك', conflict: 'يراجع المنظمون الصورتين', proofAsked: 'طلب المنظمون صورة أوضح', won: 'فوز', lost: 'خسارة',
  report: 'أرسل النتيجة', reportT: 'أرسل نتيجة المباراة', reportSub: 'أدخل النتيجة وارفع صورة لشاشة النتيجة. يراجعها المنظمون قبل تحديث الشجرة.', shot: 'صورة النتيجة', drop: 'اختر صورة أو اسحبها هنا', replace: 'اختر صورة أخرى', submitReport: 'أرسل للمراجعة', cancel: 'إلغاء', reported: 'تم الإرسال. سيراجعها المنظمون قريباً.', reportedYou: (a, b) => `أرسلت النتيجة ${a}–${b}.`,
  checkInBtn: 'سجّل حضورك', checkInOpen: 'تسجيل الحضور مفتوح. سجّل حضورك قبل البدء وإلا فلن تكون في الشجرة.', checkedIn: 'تم تسجيل الحضور', checkInLater: (d) => `يفتح تسجيل الحضور ${d}.`,
  withdrawBtn: 'انسحب', withdrawQ: 'الانسحاب من هذه البطولة؟', withdrawCaptain: 'ينسحب فريقك بالكامل ويُلغى مكانه.', withdrawSolo: 'يُلغى مكانك.', withdrawRefund: 'تُسترد رسوم الاشتراك، ولا تُسترد رسوم الحجز.', keep: 'احتفظ بمكاني', withdrawn: 'لقد انسحبت.',
  teamCodeLine: (c) => `رمز الفريق ${c}`, members: (n, of) => `${n} من ${of} لاعبين`,
  placeLine: (p) => `أنهيت في ${p}`, noMatchYet: 'تظهر مباراتك الأولى هنا عند بدء البطولة.', eliminated: 'انتهى مشوارك في هذه البطولة.',
  paid: 'تم الدفع. أنت مسجّل.', payFailed: 'لم يتم الدفع ولم يُخصم أي مبلغ. حاول مجدداً من مبارياتي.', payCancelled: 'أُلغي الدفع. لم يُخصم أي مبلغ.', payPending: 'بانتظار تأكيد الدفع. تتحدث هذه الصفحة عند التأكيد.',
  offlineT: 'هذا الموقع غير متاح', offlineP: 'يحدّث المنظمون خطتهم. عد قريباً.',
  verifiedNote: 'يوثّق المنظمون الحسابات الجديدة؛ بعض البطولات متاحة للاعبين الموثقين فقط.',
};

export const playText = (l: 'en' | 'ar') => (l === 'ar' ? ar : en);
