/**
 * Interface text for public event websites, in English and Arabic.
 *
 * Organiser content (event name, pages, biographies, ticket names) is shown
 * as written. Everything else comes from here, so an Arabic site reads as
 * Arabic from the menu to the error messages. The English strings are the
 * product's existing copy; the Arabic should be reviewed by a native editor
 * before launch.
 */
import type { EventTypeDef, EventTypeKey } from './event-types';
import type { Locale } from './time';

interface Vocab {
  label: string;
  people: string;
  unit: string;
  units: string;
  idName: string;
  badge: string;
  one: string;
  afterLbl: string;
  chair: string;
  f1: string;
  f2: string;
  role: string;
}

/** Arabic words by type, mirroring the English in event-types.ts. */
const AR: Record<EventTypeKey, Vocab> = {
  medical: { label: 'مؤتمر طبي', people: 'المحاضرون', unit: 'الجلسة', units: 'جلسات', idName: 'رقم التسجيل', badge: 'البطاقة', one: 'التسجيل', afterLbl: 'إصدار الشهادات', chair: 'رئاسة الجلسة', f1: 'التخصص', f2: 'المستشفى أو المركز', role: 'مشارك' },
  conference: { label: 'مؤتمر', people: 'المتحدثون', unit: 'الجلسة', units: 'جلسات', idName: 'رقم التذكرة', badge: 'البطاقة', one: 'التذكرة', afterLbl: 'إصدار الشهادات', chair: 'مع', f1: 'المجال', f2: 'الاستوديو أو الشركة', role: 'مشارك' },
  summit: { label: 'قمة أو فعالية أعمال', people: 'المتحدثون', unit: 'الجلسة', units: 'جلسات', idName: 'رقم التذكرة', badge: 'البطاقة', one: 'التذكرة', afterLbl: 'صفحة ما بعد الفعالية', chair: 'المتحدثون', f1: 'الدور', f2: 'الشركة', role: 'مشارك' },
  concert: { label: 'حفل أو مهرجان', people: 'الفنانون', unit: 'المدخل', units: 'مداخل', idName: 'رقم التذكرة', badge: 'التذكرة الإلكترونية', one: 'التذكرة', afterLbl: 'صفحة ما بعد الحفل', chair: 'يقبل', f1: 'التذكرة', f2: 'المدينة', role: '' },
  workshop: { label: 'ورشة عمل أو تدريب', people: 'المدربون', unit: 'الجلسة', units: 'جلسات', idName: 'رقم التذكرة', badge: 'البطاقة', one: 'التذكرة', afterLbl: 'إصدار الشهادات', chair: 'مع', f1: 'المجال', f2: 'الاستوديو أو الشركة', role: 'مشارك' },
  exhibition: { label: 'معرض', people: 'العارضون', unit: 'المدخل', units: 'مداخل', idName: 'رقم التذكرة', badge: 'البطاقة', one: 'الزائر', afterLbl: 'تقارير الزوار', chair: 'مع', f1: 'المجال', f2: 'الشركة', role: 'زائر' },
  gala: { label: 'حفل أو إطلاق', people: 'المضيفون', unit: 'المدخل', units: 'مداخل', idName: 'رقم التذكرة', badge: 'البطاقة', one: 'الضيف', afterLbl: 'صفحة ما بعد الفعالية', chair: 'المتحدثون', f1: 'الدور', f2: 'الشركة', role: 'ضيف' },
};

/** Category and highlight names that come from the type, not the organiser. */
const AR_TERMS: Record<string, string> = {
  International: 'محاضرون دوليون', Regional: 'محاضرون إقليميون', Local: 'محاضرون محليون',
  Keynote: 'متحدث رئيسي', Speaker: 'متحدث', 'Workshop lead': 'قائد ورشة', Panellist: 'محاور', 'Pitch judge': 'محكّم',
  Headliner: 'الفنان الرئيسي', Support: 'فنان مشارك', 'Opening set': 'الافتتاح',
  'Lead trainer': 'المدرب الرئيسي', Trainer: 'مدرب', Assistant: 'مساعد', 'Hall 1': 'القاعة 1', 'Hall 2': 'القاعة 2', Outdoor: 'الساحة الخارجية',
  Host: 'المضيف', Performer: 'مؤدٍّ', 'Guest of honour': 'ضيف الشرف',
  'Meeting director': 'مدير الاجتماع', 'Meeting co-director': 'نائب مدير الاجتماع', 'Headline keynote': 'المتحدث الرئيسي',
  'Also appearing': 'يشارك أيضًا',
  // Built-in form field labels, when the organiser hasn't renamed them.
  Title: 'اللقب', 'First name': 'الاسم الأول', 'Last name': 'اسم العائلة', Email: 'البريد الإلكتروني', Mobile: 'رقم الجوال', Ticket: 'التذكرة',
  Speciality: 'التخصص', 'Hospital / centre': 'المستشفى أو المركز', Discipline: 'المجال', 'Studio / company': 'الاستوديو أو الشركة', Role: 'الدور', Company: 'الشركة', City: 'المدينة',
  'Medical licence number': 'رقم الترخيص الطبي', 'Dietary requirements': 'متطلبات غذائية', 'Date of birth': 'تاريخ الميلاد', Gender: 'الجنس',
  'Company stage': 'مرحلة الشركة', 'LinkedIn profile': 'حساب لينكدإن', 'Job title': 'المسمى الوظيفي', 'Accessibility needs': 'احتياجات الوصول',
  Female: 'أنثى', Male: 'ذكر', 'Prefer not to say': 'أفضّل عدم الإجابة', Prof: 'أ.د.', Dr: 'د.', Mr: 'السيد', Mrs: 'السيدة', Ms: 'الآنسة',
};

const n = (x: number) => x.toLocaleString('en-US');

export function siteText(TY: EventTypeDef, locale: Locale) {
  return locale === 'ar' ? arabic(TY) : english(TY);
}

export type SiteText = ReturnType<typeof english>;

function english(TY: EventTypeDef) {
  const lower = (s: string) => s.charAt(0).toLowerCase() + s.slice(1);
  const idl = lower(TY.idName);
  const tickets = TY.openForm === 'Tickets';
  return {
    locale: 'en' as Locale,
    dir: 'ltr' as 'ltr' | 'rtl',
    v: { label: TY.label, people: TY.people, unit: TY.unit, units: TY.units, idName: TY.idName, badge: TY.badge, one: TY.one, afterLbl: TY.afterLbl, chair: TY.chair, role: TY.role },
    term: (s: string) => s,
    catHeading: (c: string) => `${c}${TY.catSfx}`,
    // Site frame
    home: 'Home',
    programmeNav: TY.gates ? 'Set times' : TY.credits ? 'Sessions' : 'Agenda',
    venue: 'Venue',
    skip: 'Skip to content',
    maintenance: `The website is being updated and will be back shortly. If you’ve registered, your confirmation email and ${TY.badge} still work.`,
    poweredBy: 'Registration and check-in by zemmz Live',
    switchTo: 'العربية',
    // Homepage panels
    claimTitle: TY.cert !== 'none' ? (TY.credits ? 'Your certificate and CME points' : 'Your certificate') : TY.gates ? 'Photos and the survey' : 'Recordings and slides',
    claimSub: TY.cert !== 'none' ? `Enter your ${idl} and email to download your certificate.` : `Enter your ${idl} and email to open the ${TY.afterLbl.toLowerCase()}.`,
    claimCta: TY.cert !== 'none' ? 'Get my certificate' : `Open the ${TY.afterLbl.toLowerCase()}`,
    claimPlaceholder: `The number on your ${TY.badge}`,
    claimEmail: 'Email you registered with',
    checking: 'Checking…',
    claimFine: 'Only people who checked in at the event can claim.',
    ticketsHeading: tickets ? 'Tickets' : 'Registration',
    nothingOnSale: 'Nothing is on sale right now. Check back soon.',
    getTickets: tickets ? 'Get tickets' : 'Register',
    register: 'Register',
    registering: 'Registering…',
    freeSub: `Free. You’ll get your ${idl} by email.`,
    howAttending: 'How you’re attending',
    consent: 'Send me news about future editions. You can unsubscribe at any time.',
    consentShort: 'Send me news about future editions.',
    freeFine: 'You’ll get a confirmation email with your ID straight away.',
    closed: tickets ? 'Ticket sales are closed' : 'Registration is closed',
    closedSub: 'If you’ve already registered, your confirmation email has everything you need.',
    perOrder: 'Up to 10 per order. Each ticket gets its own ID.',
    onlyLeft: (x: number) => ` · only ${x} left`,
    soldOut: 'Sold out',
    ticketsOf: (name: string) => `${name} tickets`,
    oneFewer: (name: string) => `One fewer ${name}`,
    oneMore: (name: string) => `One more ${name}`,
    ticketCount: (x: number) => `${x} ${x === 1 ? 'ticket' : 'tickets'}`,
    chooseTickets: 'Choose tickets',
    continue: 'Continue',
    feeFine: 'A booking fee is shown before you pay.',
    // Homepage sections
    kickPeople: TY.people.toUpperCase(),
    allPeople: `All ${TY.people.toLowerCase()}`,
    kickProgramme: TY.gates ? 'THE NIGHT' : 'PROGRAMME',
    programmeTitle: (days: number, count: number) => (TY.gates ? 'Doors and gates' : `${days} ${days === 1 ? 'day' : 'days'}, ${count} ${TY.units}`),
    onNow: TY.gates ? 'Open now' : 'On now',
    seats: (x: number) => `${n(x)} seats`,
    fullProgramme: `Full ${TY.gates ? 'set times' : 'programme'}`,
    // Form fields
    optional: 'optional',
    chooseTicket: 'Choose a ticket',
    chooseOne: 'Choose one',
    notGiven: 'Not given',
    // Checkout
    backToEvent: 'Back to the event',
    steps: (free: boolean) => ['Tickets', 'Your details', free ? 'Confirm' : 'Payment'],
    promo: 'Promo code',
    apply: 'Apply',
    percentOff: (code: string, pct: number) => `${code}: ${pct}% off`,
    yourDetails: 'Your details',
    nameOnEach: 'Name on each ticket',
    nameOnEachSub: (gates: boolean) => `Each ticket gets its own ${idl}${gates ? ' and barcode' : ''}. Leave blank to use your name.`,
    firstName: 'First name',
    lastName: 'Last name',
    back: 'Back',
    confirm: 'Confirm',
    confirming: 'Confirming…',
    testPayments: 'Test payments.',
    testPaymentsBody: 'No payment provider is connected yet, so no card details are asked for and nothing is charged. A regional provider’s secure card form goes here.',
    paying: 'Paying…',
    pay: (amount: string) => `Pay ${amount}`,
    applePay: 'Pay with Apple Pay',
    tryDecline: 'Try a declined payment',
    emailedFine: `Your tickets and ${idl}s are emailed as soon as the order is confirmed.`,
    stepOf: (i: number, name: string) => `Step ${i} of 3: ${name}`,
    workingOut: 'Working out the total…',
    chooseOneTicket: 'Choose at least one ticket.',
    discount: (code: string) => `Discount (${code})`,
    bookingFee: 'Booking fee',
    total: 'Total',
    // Programme, venue, people
    setTimes: 'Set times',
    timesAre: (tz: string) => `Times are ${tz.replace('_', ' ')}.`,
    doorsOpen: (t: string) => ` Doors open ${t}.`,
    tbc: 'TBC',
    gates: 'Gates',
    gatesSub: (passOuts: boolean) => `Your e-ticket works only at the gate for your ticket type.${passOuts ? ' Pass-outs are allowed: scan out and back in.' : ' There are no pass-outs: once you leave, you can’t come back in.'}`,
    programmeTitlePage: TY.credits ? 'Sessions' : 'Agenda',
    cmeNote: ' Scan in and out at the door of each session: CME points depend on time in the room.',
    comingSoon: 'The programme will be published soon.',
    cmePoints: (x: number) => `${x} CME points`,
    telephone: 'Telephone:',
    googleMaps: 'Directions in Google Maps',
    appleMaps: 'Apple Maps',
    peopleSub: TY.gates ? 'Who’s playing, in running order.' : 'Select a name to read their biography.',
    peopleSoon: `The ${TY.people.toLowerCase()} will be announced soon.`,
    // Tickets and orders
    cancelledTicket: `This ${TY.one} was cancelled and can’t be used at the door.`,
    registered: 'You’re registered',
    emailedTo: (email: string) => `We’ve emailed this to ${email}. Keep your ${idl} for ${TY.gates ? 'the gate' : 'the registration desk'}.`,
    printBadge: `Print or save the ${TY.badge}`,
    paymentReceived: 'Payment received. ',
    youreIn: 'You’re in',
    orderLine: (count: number, email: string) => `${count} ${count === 1 ? 'ticket' : 'tickets'}, each with its own ${idl}. We’ve emailed ${email}.`,
    paidLine: (total: string, fee: string | null, off: string | null, ref: string) => `Paid ${total}${fee ? `, including a ${fee} booking fee` : ''}${off ? ` and ${off} off` : ''}. Reference ${ref}.`,
    printAll: `Print all ${TY.badge}s`,
    openAlone: `Open this ${TY.badge} on its own`,
    // Badge and certificate
    badgeKicker: TY.gates ? 'E-TICKET' : TY.role || 'BADGE',
    entry: (gate: string) => `Entry: ${gate}`,
    certifyThat: 'This is to certify that',
    activityNumber: 'Activity number',
    // After the event
    afterKick: TY.afterLbl.toUpperCase(),
    thankYou: (name: string) => `Thank you, ${name}`,
    recordingsAndSlides: (rec: boolean, slides: boolean): string => (rec && slides ? 'Recordings and slides' : rec ? 'Recordings' : 'Slides'),
    watch: 'Watch the recording',
    downloadSlides: 'Download the slides (PDF)',
    notYet: 'The organiser hasn’t added them yet. Check back soon.',
    photos: 'Photos',
    photosSoon: 'The official photos are on their way. Check back soon.',
    survey: 'Two-minute survey',
    surveyThanks: 'Thanks, we’ve got your answers.',
    surveyNotReady: 'The survey isn’t ready yet.',
    certNotReady: 'The certificate isn’t ready yet. Try again later.',
    tooFewSessions: (attended: number, need: number, id: number) => `You attended ${attended} ${TY.units}; the certificate needs ${need}. If you think this is wrong, contact the organiser with your ${idl} ${id}.`,
    step1of2: 'STEP 1 OF 2',
    evaluation: 'Evaluation',
    evaluationIntro: `Your certificate is ready. ${TY.credits ? 'Accreditation requires an evaluation first.' : 'Please tell us how it went first.'} It takes about three minutes.`,
    stillCounting: (title: string, ends: string) => `Your CME points are still being counted: you’re checked in to ${title}, which ends at ${ends}. Come back after it ends to get your certificate.`,
    yourCertificate: 'Your certificate',
    pointsLine: (credits: number, count: number) => `${credits} CME points from ${count} ${count === 1 ? TY.unit.toLowerCase() : TY.units}.`,
    forLine: (what: string) => `For ${what}.`,
    sessionsCount: (x: number) => `${x} ${TY.units}`,
    printPdf: 'Print or save as PDF',
    scale: ['Poor', 'Fair', 'Good', 'Very good', 'Excellent'],
    tickAny: 'Tick any that apply',
    sending: 'Sending…',
    submit: 'Submit',
    // Server messages
    err: {
      busy: 'Too many attempts from this connection. Wait a few minutes and try again.',
      generic: 'Something went wrong. Please try again.',
      regClosed: 'Registration has closed.',
      salesClosed: 'Ticket sales have closed.',
      sellsTickets: 'This event sells tickets. Choose them above.',
      chooseAttending: 'Choose how you’re attending',
      checkFields: 'Check the highlighted fields.',
      alreadyRegistered: (email: string) => `${email} is already registered. We’ve sent the confirmation email again, with your ${idl}.`,
      promoInvalid: (code: string) => `The code ${code} isn’t valid for this event.`,
      chooseTicket: 'Choose at least one ticket.',
      afterNotOpen: `The ${TY.afterLbl.toLowerCase()} isn’t open yet.`,
      enterNumber: `Enter the number on your ${TY.badge}`,
      enterEmail: 'Enter the email you registered with',
      notFound: (id: number) => `We couldn’t find ${idl} ${id} with that email. Check both against your confirmation email.`,
      cancelled: `This ${TY.one} was cancelled, so there’s nothing to claim.`,
      noShowAfter: `Our records show you booked but didn’t check in, so the recordings aren’t available to you. If you were there, contact the organiser with your ${idl}.`,
      noShowCert: `Our records show you registered but didn’t check in to any ${TY.unit.toLowerCase()}, so we can’t issue a certificate. If you were there, contact the organiser with your ${idl}.`,
      linkExpired: 'This link has expired. Claim again from the homepage.',
      answerThis: 'Answer this question',
      answerRequired: 'Answer the required questions.',
      enterYour: (label: string) => `Enter your ${label.toLowerCase()}`,
      chooseYour: (label: string) => `Choose your ${label.toLowerCase()}`,
      chooseOption: (label: string) => `Choose one of the options for ${label.toLowerCase()}`,
      dateFormat: 'Enter a date like 2000-01-31',
      email: 'Enter an email address like name@example.com',
      mobile: 'Enter a mobile number with its country code, like +971 50 123 4567',
      paused: 'Registration for this event is paused for now. Contact the organiser.',
    },
    // Emails
    mail: { showBadge: `Show my ${TY.badge}`, idName: TY.idName },
    payment: {
      vat: (pct: string) => `VAT (${pct})`,
      securePage: (provider: string) => `You’ll pay on ${provider}’s secure page. Card details never reach the organiser or zemmz.`,
      testMode: 'Test mode: the next page lets you approve or decline a payment. No card details are asked for and nothing is charged.',
      toPayment: (amount: string) => `Continue to payment, ${amount}`,
      redirecting: 'Opening the payment page…',
      feeNotRefundable: 'The booking fee isn’t refundable.',
      refundPolicy: (hours: number | null) => hours == null ? 'Tickets can’t be refunded online. Contact the organiser if you can’t attend.' : `You can cancel and get a refund online until ${hours} hours before the start.`,
      checkingTitle: 'Checking your payment',
      checkingBody: 'The payment provider hasn’t confirmed the payment yet. This page checks again every few seconds. Don’t pay a second time.',
      cancelled: 'The payment was cancelled and nothing was charged. Your details are still here: try again when you’re ready.',
      failed: (why: string) => `The payment didn’t go through${why ? `: ${why}` : '.'} Nothing was charged. Try again or use another card.`,
      expired: 'Your tickets were held for 45 minutes and the payment didn’t arrive in time, so they were released. Nothing was charged. Start again to get tickets.',
      testTitle: 'Test payment',
      testBody: 'This page stands in for the payment provider while zemmz is in test mode. Nothing is charged.',
      approve: (amount: string) => `Approve ${amount}`,
      decline: 'Decline the payment',
      receipt: 'Receipt',
      taxInvoice: 'Tax invoice',
      invoiceNo: 'Invoice number',
      issued: 'Issued',
      billedTo: 'Billed to',
      seller: 'Seller',
      trn: 'VAT number',
      item: 'Item',
      amount: 'Amount',
      subtotal: 'Subtotal',
      paidWith: (provider: string, ref: string) => `Paid through ${provider}. Reference ${ref}.`,
      refunded: (amount: string) => `Refunded ${amount}`,
      refundedTicket: 'Refunded',
      cancelTicket: 'Cancel and get a refund',
      cancelConfirm: (amount: string) => `Cancel this ticket and refund ${amount} to the card you paid with? The ticket stops working straight away.`,
      cancelDone: (amount: string) => `Cancelled. ${amount} is on its way back to your card; banks usually take 5 to 10 working days.`,
      cancelTooLate: (hours: number) => `Online refunds closed ${hours} hours before the start. Contact the organiser.`,
      cancelUsed: 'This ticket has already been used, so it can’t be refunded online.',
      refundFailed: 'The refund didn’t go through and your ticket is still valid. Try again in a few minutes or contact the organiser.',
      mailRefundSubject: (event: string) => `Refund for ${event}`,
      mailRefundKicker: 'REFUND',
      mailRefundBody: (amount: string, ids: string) => `We’ve refunded ${amount} to the card you paid with, for ${ids}. Those tickets no longer work. Banks usually take 5 to 10 working days to show a refund.`,
    },
  };
}

function arabic(TY: EventTypeDef): SiteText {
  const a = AR[TY.key];
  const tickets = TY.openForm === 'Tickets';
  const en = english(TY);
  const count = (x: number, one: string, two: string, many: string) => (x === 1 ? one : x === 2 ? two : `${n(x)} ${many}`);
  return {
    ...en,
    locale: 'ar',
    dir: 'rtl',
    v: { label: a.label, people: a.people, unit: a.unit, units: a.units, idName: a.idName, badge: a.badge, one: a.one, afterLbl: a.afterLbl, chair: a.chair, role: a.role },
    term: (s: string) => AR_TERMS[s] ?? (s === TY.f1 ? a.f1 : s === TY.f2 ? a.f2 : s),
    catHeading: (c: string) => AR_TERMS[c] ?? c,
    home: 'الرئيسية',
    programmeNav: TY.gates ? 'مواعيد العروض' : TY.credits ? 'الجلسات' : 'البرنامج',
    venue: 'المكان',
    skip: 'انتقل إلى المحتوى',
    maintenance: `يجري تحديث الموقع وسيعود قريبًا. إذا كنت قد سجّلت، فإن بريد التأكيد و${a.badge} لا يزالان صالحين.`,
    poweredBy: 'التسجيل والدخول عبر zemmz Live',
    switchTo: 'English',
    claimTitle: TY.cert !== 'none' ? (TY.credits ? 'شهادتك ونقاط التعليم الطبي المستمر' : 'شهادتك') : TY.gates ? 'الصور والاستبيان' : 'التسجيلات والعروض التقديمية',
    claimSub: TY.cert !== 'none' ? `أدخل ${a.idName} والبريد الإلكتروني لتنزيل شهادتك.` : `أدخل ${a.idName} والبريد الإلكتروني لفتح ${a.afterLbl}.`,
    claimCta: TY.cert !== 'none' ? 'احصل على شهادتي' : `افتح ${a.afterLbl}`,
    claimPlaceholder: `الرقم المطبوع على ${a.badge}`,
    claimEmail: 'البريد الإلكتروني الذي سجّلت به',
    checking: 'جارٍ التحقق…',
    claimFine: 'يمكن فقط لمن سجّل حضوره في الفعالية الحصول عليها.',
    ticketsHeading: tickets ? 'التذاكر' : 'التسجيل',
    nothingOnSale: 'لا توجد تذاكر معروضة الآن. عُد لاحقًا.',
    getTickets: tickets ? 'احجز تذاكرك' : 'سجّل الآن',
    register: 'سجّل الآن',
    registering: 'جارٍ التسجيل…',
    freeSub: `مجاني. سيصلك ${a.idName} بالبريد الإلكتروني.`,
    howAttending: 'نوع الحضور',
    consent: 'أرسلوا لي أخبار الدورات القادمة. يمكنني إلغاء الاشتراك في أي وقت.',
    consentShort: 'أرسلوا لي أخبار الدورات القادمة.',
    freeFine: 'سيصلك بريد تأكيد برقمك فورًا.',
    closed: tickets ? 'انتهى بيع التذاكر' : 'التسجيل مغلق',
    closedSub: 'إذا كنت قد سجّلت، فستجد كل ما تحتاجه في بريد التأكيد.',
    perOrder: 'حتى 10 تذاكر في الطلب الواحد، ولكل تذكرة رقمها الخاص.',
    onlyLeft: (x: number) => ` · بقي ${n(x)} فقط`,
    soldOut: 'نفدت',
    ticketsOf: (name: string) => `تذاكر ${name}`,
    oneFewer: (name: string) => `تذكرة ${name} أقل`,
    oneMore: (name: string) => `تذكرة ${name} إضافية`,
    ticketCount: (x: number) => count(x, 'تذكرة واحدة', 'تذكرتان', x <= 10 ? 'تذاكر' : 'تذكرة'),
    chooseTickets: 'اختر التذاكر',
    continue: 'متابعة',
    feeFine: 'تظهر رسوم الحجز قبل الدفع.',
    kickPeople: a.people,
    allPeople: `جميع ${a.people}`,
    kickProgramme: TY.gates ? 'الليلة' : 'البرنامج',
    programmeTitle: (days: number, c: number) => (TY.gates ? 'الأبواب والبوابات' : `${count(days, 'يوم واحد', 'يومان', 'أيام')}، ${n(c)} ${a.units}`),
    onNow: TY.gates ? 'مفتوح الآن' : 'جارية الآن',
    seats: (x: number) => `${n(x)} مقعدًا`,
    fullProgramme: TY.gates ? 'جميع مواعيد العروض' : 'البرنامج الكامل',
    optional: 'اختياري',
    chooseTicket: 'اختر التذكرة',
    chooseOne: 'اختر واحدًا',
    notGiven: 'غير محدد',
    backToEvent: 'العودة إلى الفعالية',
    steps: (free: boolean) => ['التذاكر', 'بياناتك', free ? 'التأكيد' : 'الدفع'],
    promo: 'رمز الخصم',
    apply: 'تطبيق',
    percentOff: (code: string, pct: number) => `${code}: خصم ${pct}٪`,
    yourDetails: 'بياناتك',
    nameOnEach: 'الاسم على كل تذكرة',
    nameOnEachSub: (gates: boolean) => `لكل تذكرة ${a.idName} خاص بها${gates ? ' ورمز شريطي' : ''}. اتركه فارغًا لاستخدام اسمك.`,
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    back: 'رجوع',
    confirm: 'تأكيد',
    confirming: 'جارٍ التأكيد…',
    testPayments: 'دفعات تجريبية.',
    testPaymentsBody: 'لم يتم ربط مزوّد دفع بعد، لذلك لا تُطلب بيانات البطاقة ولا يُخصم أي مبلغ. سيظهر هنا نموذج البطاقة الآمن من مزوّد الدفع.',
    paying: 'جارٍ الدفع…',
    pay: (amount: string) => `ادفع ${amount}`,
    applePay: 'الدفع عبر Apple Pay',
    tryDecline: 'جرّب دفعة مرفوضة',
    emailedFine: 'تصلك التذاكر وأرقامها بالبريد الإلكتروني فور تأكيد الطلب.',
    stepOf: (i: number, name: string) => `الخطوة ${i} من 3: ${name}`,
    workingOut: 'جارٍ حساب المجموع…',
    chooseOneTicket: 'اختر تذكرة واحدة على الأقل.',
    discount: (code: string) => `خصم (${code})`,
    bookingFee: 'رسوم الحجز',
    total: 'المجموع',
    setTimes: 'مواعيد العروض',
    timesAre: (tz: string) => `الأوقات بتوقيت ${tz.split('/').pop()!.replace('_', ' ')}.`,
    doorsOpen: (t: string) => ` تُفتح الأبواب الساعة ${t}.`,
    tbc: 'يُحدد لاحقًا',
    gates: 'البوابات',
    gatesSub: (passOuts: boolean) => `تعمل تذكرتك الإلكترونية فقط عند البوابة المخصصة لنوع تذكرتك.${passOuts ? ' يُسمح بالخروج والعودة: امسح عند الخروج وعند العودة.' : ' لا يُسمح بالعودة بعد الخروج.'}`,
    programmeTitlePage: TY.credits ? 'الجلسات' : 'البرنامج',
    cmeNote: ' امسح بطاقتك عند دخول كل جلسة والخروج منها: تعتمد نقاط التعليم الطبي المستمر على مدة الحضور.',
    comingSoon: 'سيُنشر البرنامج قريبًا.',
    cmePoints: (x: number) => `${x} نقاط تعليم طبي مستمر`,
    telephone: 'الهاتف:',
    googleMaps: 'الاتجاهات في خرائط Google',
    appleMaps: 'خرائط Apple',
    peopleSub: TY.gates ? 'الفنانون حسب ترتيب الظهور.' : 'اختر اسمًا لقراءة السيرة الذاتية.',
    peopleSoon: `سيُعلن عن ${a.people} قريبًا.`,
    cancelledTicket: `أُلغي ${a.one} ولا يمكن استخدامه عند الدخول.`,
    registered: 'تم تسجيلك',
    emailedTo: (email: string) => `أرسلنا هذه إلى ${email}. احتفظ بـ${a.idName} ${TY.gates ? 'لتقديمه عند البوابة' : 'لتقديمه في مكتب التسجيل'}.`,
    printBadge: `اطبع ${a.badge} أو احفظها`,
    paymentReceived: 'تم استلام الدفع. ',
    youreIn: 'حجزك مؤكد',
    orderLine: (c: number, email: string) => `${count(c, 'تذكرة واحدة', 'تذكرتان', c <= 10 ? 'تذاكر' : 'تذكرة')}، لكل منها ${a.idName} خاص. أرسلناها إلى ${email}.`,
    paidLine: (total: string, fee: string | null, off: string | null, ref: string) => `دُفع ${total}${fee ? `، شاملًا رسوم حجز ${fee}` : ''}${off ? ` وخصمًا قدره ${off}` : ''}. المرجع ${ref}.`,
    printAll: 'اطبع جميع التذاكر',
    openAlone: `افتح ${a.badge} وحدها`,
    badgeKicker: TY.gates ? 'تذكرة إلكترونية' : a.role || 'بطاقة',
    entry: (gate: string) => `الدخول: ${gate}`,
    certifyThat: 'نشهد بأن',
    activityNumber: 'رقم النشاط',
    afterKick: a.afterLbl,
    thankYou: (name: string) => `شكرًا لك، ${name}`,
    recordingsAndSlides: (rec: boolean, slides: boolean) => (rec && slides ? 'التسجيلات والعروض التقديمية' : rec ? 'التسجيلات' : 'العروض التقديمية'),
    watch: 'شاهد التسجيل',
    downloadSlides: 'نزّل العرض التقديمي (PDF)',
    notYet: 'لم يضفها المنظم بعد. عُد لاحقًا.',
    photos: 'الصور',
    photosSoon: 'الصور الرسمية في الطريق. عُد لاحقًا.',
    survey: 'استبيان من دقيقتين',
    surveyThanks: 'شكرًا، وصلتنا إجاباتك.',
    surveyNotReady: 'الاستبيان غير جاهز بعد.',
    certNotReady: 'الشهادة غير جاهزة بعد. حاول لاحقًا.',
    tooFewSessions: (attended: number, need: number, id: number) => `حضرت ${n(attended)} ${a.units}، والشهادة تتطلب ${n(need)}. إذا كنت تعتقد أن هناك خطأ، فتواصل مع المنظم مع ذكر ${a.idName} ${id}.`,
    step1of2: 'الخطوة 1 من 2',
    evaluation: 'التقييم',
    evaluationIntro: `شهادتك جاهزة. ${TY.credits ? 'يتطلب الاعتماد تعبئة التقييم أولًا.' : 'نرجو أن تخبرنا برأيك أولًا.'} يستغرق ذلك نحو ثلاث دقائق.`,
    stillCounting: (title: string, ends: string) => `لا تزال نقاطك قيد الاحتساب: أنت مسجّل في ${title} التي تنتهي الساعة ${ends}. عُد بعد انتهائها للحصول على شهادتك.`,
    yourCertificate: 'شهادتك',
    pointsLine: (credits: number, c: number) => `${credits} نقاط تعليم طبي مستمر من ${n(c)} ${a.units}.`,
    forLine: (what: string) => `عن ${what}.`,
    sessionsCount: (x: number) => `${n(x)} ${a.units}`,
    printPdf: 'اطبع أو احفظ بصيغة PDF',
    scale: ['ضعيف', 'مقبول', 'جيد', 'جيد جدًا', 'ممتاز'],
    tickAny: 'اختر كل ما ينطبق',
    sending: 'جارٍ الإرسال…',
    submit: 'إرسال',
    err: {
      busy: 'محاولات كثيرة من هذا الاتصال. انتظر بضع دقائق ثم حاول مجددًا.',
      generic: 'حدث خطأ. حاول مجددًا.',
      regClosed: 'التسجيل مغلق.',
      salesClosed: 'انتهى بيع التذاكر.',
      sellsTickets: 'تبيع هذه الفعالية تذاكر. اخترها في الأعلى.',
      chooseAttending: 'اختر نوع الحضور',
      checkFields: 'راجع الحقول المحددة.',
      alreadyRegistered: (email: string) => `${email} مسجّل بالفعل. أعدنا إرسال بريد التأكيد مع ${a.idName}.`,
      promoInvalid: (code: string) => `الرمز ${code} غير صالح لهذه الفعالية.`,
      chooseTicket: 'اختر تذكرة واحدة على الأقل.',
      afterNotOpen: `${a.afterLbl} غير متاحة بعد.`,
      enterNumber: `أدخل الرقم المطبوع على ${a.badge}`,
      enterEmail: 'أدخل البريد الإلكتروني الذي سجّلت به',
      notFound: (id: number) => `لم نجد ${a.idName} ${id} بهذا البريد الإلكتروني. تحقق من كليهما في بريد التأكيد.`,
      cancelled: `أُلغي ${a.one}، لذا لا يوجد ما يمكن استلامه.`,
      noShowAfter: `تُظهر سجلاتنا أنك حجزت لكنك لم تسجّل حضورك، لذا لا تتوفر لك التسجيلات. إذا كنت حاضرًا، فتواصل مع المنظم مع ذكر ${a.idName}.`,
      noShowCert: `تُظهر سجلاتنا أنك سجّلت لكنك لم تحضر أي جلسة، لذا لا يمكننا إصدار شهادة. إذا كنت حاضرًا، فتواصل مع المنظم مع ذكر ${a.idName}.`,
      linkExpired: 'انتهت صلاحية هذا الرابط. اطلبه مجددًا من الصفحة الرئيسية.',
      answerThis: 'أجب عن هذا السؤال',
      answerRequired: 'أجب عن الأسئلة المطلوبة.',
      enterYour: (label: string) => `أدخل ${label}`,
      chooseYour: (label: string) => `اختر ${label}`,
      chooseOption: (label: string) => `اختر أحد خيارات ${label}`,
      dateFormat: 'أدخل التاريخ بصيغة 2000-01-31',
      email: 'أدخل بريدًا إلكترونيًا مثل name@example.com',
      mobile: 'أدخل رقم الجوال مع رمز الدولة، مثل ‎+971 50 123 4567',
      paused: 'التسجيل في هذه الفعالية متوقف مؤقتًا. تواصل مع المنظم.',
    },
    mail: { showBadge: `اعرض ${a.badge}`, idName: a.idName },
    payment: {
      vat: (pct: string) => `ضريبة القيمة المضافة (${pct})`,
      securePage: (provider: string) => `ستدفع عبر صفحة ${provider} الآمنة. لا تصل بيانات بطاقتك إلى المنظم ولا إلى zemmz.`,
      testMode: 'وضع تجريبي: تتيح لك الصفحة التالية قبول الدفعة أو رفضها. لا تُطلب بيانات البطاقة ولا يُخصم أي مبلغ.',
      toPayment: (amount: string) => `المتابعة إلى الدفع، ${amount}`,
      redirecting: 'جارٍ فتح صفحة الدفع…',
      feeNotRefundable: 'رسوم الحجز غير قابلة للاسترداد.',
      refundPolicy: (hours: number | null) => hours == null ? 'لا يمكن استرداد قيمة التذاكر عبر الإنترنت. تواصل مع المنظم إن لم تتمكن من الحضور.' : `يمكنك الإلغاء واسترداد المبلغ عبر الإنترنت حتى ${hours} ساعة قبل البدء.`,
      checkingTitle: 'نتحقق من دفعتك',
      checkingBody: 'لم يؤكد مزوّد الدفع الدفعة بعد. تتحقق هذه الصفحة مجددًا كل بضع ثوانٍ. لا تدفع مرة ثانية.',
      cancelled: 'أُلغيت الدفعة ولم يُخصم أي مبلغ. بياناتك محفوظة هنا، فحاول مجددًا عندما تكون جاهزًا.',
      failed: (why: string) => `لم تكتمل الدفعة${why ? `: ${why}` : '.'} لم يُخصم أي مبلغ. حاول مجددًا أو استخدم بطاقة أخرى.`,
      expired: 'حُجزت تذاكرك لمدة 45 دقيقة ولم تصل الدفعة في الوقت المحدد، فأُتيحت لغيرك. لم يُخصم أي مبلغ. ابدأ من جديد للحصول على التذاكر.',
      testTitle: 'دفعة تجريبية',
      testBody: 'تحل هذه الصفحة محل مزوّد الدفع أثناء الوضع التجريبي. لا يُخصم أي مبلغ.',
      approve: (amount: string) => `قبول ${amount}`,
      decline: 'رفض الدفعة',
      receipt: 'الإيصال',
      taxInvoice: 'فاتورة ضريبية',
      invoiceNo: 'رقم الفاتورة',
      issued: 'تاريخ الإصدار',
      billedTo: 'إلى',
      seller: 'البائع',
      trn: 'الرقم الضريبي',
      item: 'البند',
      amount: 'المبلغ',
      subtotal: 'المجموع الفرعي',
      paidWith: (provider: string, ref: string) => `دُفع عبر ${provider}. المرجع ${ref}.`,
      refunded: (amount: string) => `تم استرداد ${amount}`,
      refundedTicket: 'مُسترد',
      cancelTicket: 'الإلغاء واسترداد المبلغ',
      cancelConfirm: (amount: string) => `هل تريد إلغاء هذه التذكرة واسترداد ${amount} إلى البطاقة التي دفعت بها؟ تتوقف التذكرة عن العمل فورًا.`,
      cancelDone: (amount: string) => `تم الإلغاء. سيُعاد ${amount} إلى بطاقتك، وعادةً تستغرق المصارف من 5 إلى 10 أيام عمل.`,
      cancelTooLate: (hours: number) => `أُغلق الاسترداد عبر الإنترنت قبل البدء بـ ${hours} ساعة. تواصل مع المنظم.`,
      cancelUsed: 'استُخدمت هذه التذكرة، لذلك لا يمكن استرداد قيمتها عبر الإنترنت.',
      refundFailed: 'لم يكتمل الاسترداد وما زالت تذكرتك صالحة. حاول بعد دقائق أو تواصل مع المنظم.',
      mailRefundSubject: (event: string) => `استرداد مبلغ: ${event}`,
      mailRefundKicker: 'استرداد',
      mailRefundBody: (amount: string, ids: string) => `أعدنا ${amount} إلى البطاقة التي دفعت بها، مقابل ${ids}. لم تعد هذه التذاكر صالحة. تستغرق المصارف عادةً من 5 إلى 10 أيام عمل لإظهار المبلغ.`,
    },
  };
}
